// <auto-generated />
using LibrosApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibrosApp.Migrations
{
    [DbContext(typeof(LibrosContext))]
    [Migration("20230713111253_InMigration")]
    partial class InMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibrosApp.Models.Author", b =>
                {
                    b.Property<int>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuthorId"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuthorId");

                    b.ToTable("Author");

                    b.HasData(
                        new
                        {
                            AuthorId = 1,
                            Country = "Francia",
                            Name = "Antoine de Saint-Exupéry"
                        });
                });

            modelBuilder.Entity("LibrosApp.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("PublicationYear")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookId");

                    b.HasIndex("AuthorId");

                    b.ToTable("Book");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            AuthorId = 1,
                            PublicationYear = "1943",
                            Title = "El principito"
                        },
                        new
                        {
                            BookId = 2,
                            AuthorId = 1,
                            PublicationYear = "1939",
                            Title = "Tierra de hombres"
                        },
                        new
                        {
                            BookId = 3,
                            AuthorId = 1,
                            PublicationYear = "1931",
                            Title = "Vuelo nocturno"
                        },
                        new
                        {
                            BookId = 4,
                            AuthorId = 1,
                            PublicationYear = "1948",
                            Title = "The Wisdom of the Sands"
                        },
                        new
                        {
                            BookId = 5,
                            AuthorId = 1,
                            PublicationYear = "1942",
                            Title = "Piloto de guerra"
                        },
                        new
                        {
                            BookId = 6,
                            AuthorId = 1,
                            PublicationYear = "1943",
                            Title = "Carta a un rehén"
                        });
                });

            modelBuilder.Entity("LibrosApp.Models.Book", b =>
                {
                    b.HasOne("LibrosApp.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("LibrosApp.Models.Author", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
